Feature: SEO for homepage and category
prezly/theme-nextjs-starter pull request #11
Opened 2021-04-05 08:30 UTC by pablopunk

2021-04-05 08:38 UTC, pablopunk commented on pages/index.tsx
> +            imageUrl={newsroom.newsroom_logo.cdnUrl}
https://linear.app/prezly/issue/DEV-2437/wrong-type-on-sdk-missing-newsroom-logo

2021-04-06 07:18 UTC, oleg-semyonov requested changes

2021-04-06 07:18 UTC, oleg-semyonov commented on modules/Story/Story.tsx
> +import { StorySeo } from '@/components/seo';
The story page doesn't have `title` attribute set. I guess it's just not passed to the component.
Other meta seems to be in place

2021-04-06 07:39 UTC, oleg-semyonov approved these changes

2021-04-06 07:40 UTC, merged